import "server-only"

import { ThinkingLevel } from "@google/genai"

import {
  generateGroundedText,
  type GroundingSource,
} from "@/lib/gemini/generate"
import { createAdminClient } from "@/lib/supabase/admin"
import type { Json } from "@/lib/supabase/types"
import {
  angleForDate,
  angleId,
  resolveAngle,
  type Angle,
  VERTICALS,
  TECH_FOCUS,
} from "@/lib/blog/topic-pillars"
import { translateFieldEnToEs } from "@/lib/blog/translate"

// House style is enforced in every system prompt — Gemini will insert em
// dashes constantly otherwise, and Vetd's marketing copy forbids them.
const HOUSE_STYLE =
  "House style: confident, plain-spoken, useful. Short sentences. No filler. " +
  "No marketing fluff. No em dashes (—). Use commas, periods, or parentheses instead. " +
  "Write for a small business owner who values their time."

const VETD_CONTEXT =
  "Vetd is a digital agency that builds websites, mobile apps, SaaS products, " +
  "and AI integrations for small businesses. Fixed scope, fixed price, no " +
  "hourly billing. We offer 0% in-house financing on projects $5,000 and up."

// Internal links the body should reference where natural — keeps content
// pulling visitors toward conversion surfaces.
const INTERNAL_LINKS = [
  "/contact (start a project)",
  "/financing (0% in-house financing on $5K plus)",
  "/#products (the four product lines)",
  "/#process (how engagements work)",
] as const

const TARGET_WORD_COUNT = "1,200 to 1,800 words"

// JSON schema embedded in the prompt rather than via responseSchema, because
// Gemini's structured output is finicky with markdown payloads. Defensive
// parser tolerates a code fence wrapper.
const JSON_INSTRUCTION = `
Return ONLY a JSON object with this exact shape, no commentary, no code fence:
{
  "title": string,
  "excerpt": string,
  "tags": string[],
  "body_md": string
}

Field rules:
- title: specific, problem-or-outcome oriented, 8 to 14 words
- excerpt: one or two sentences, max 155 characters, used as the meta description
- tags: 3 to 5 lowercase strings, 1 to 3 words each
- body_md: full markdown body, ${TARGET_WORD_COUNT}, structured with:
  - one short intro paragraph (no heading)
  - 4 to 6 H2 sections (## Heading), with sub-bullets or H3 (### Heading) where useful
  - one short conclusion paragraph that includes a soft call to action
  - reference at least one of these internal links naturally where it fits:
    ${INTERNAL_LINKS.join(", ")}
  - do not include the title as an H1 inside body_md (the title field is the H1)`

export type AutoGeneratedPost = {
  title: string
  excerpt: string
  tags: string[]
  body_md: string
}

export type GenerateDailyResult =
  | {
      ok: true
      postId: string
      slug: string
      verticalId: string
      techId: string
      title: string
      mode: "draft" | "scheduled"
      sourceCount: number
      /**
       * Per-field translation status. EN-only posts (every field undefined)
       * happen when translation was skipped via options.translate=false or
       * if every Gemini ES call failed; the row was still inserted.
       */
      translation: {
        title: boolean
        excerpt: boolean
        body: boolean
      }
    }
  | {
      ok: false
      error: string
      verticalId?: string
      techId?: string
    }

/**
 * Slugify a title to URL-safe lowercase. Mirrors the helper in the editor —
 * kept here separately to avoid importing client code into a server module.
 */
function titleToSlug(title: string): string {
  return title
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80)
}

/**
 * Strip a leading/trailing JSON code fence if Gemini ignored the "no code
 * fence" instruction. Also handles the model occasionally prefixing with
 * "Here is the JSON:" or similar.
 */
function extractJsonPayload(raw: string): string {
  let cleaned = raw.trim()
  // Drop a leading code fence (```json or ```).
  cleaned = cleaned.replace(/^```(?:json)?\s*/i, "")
  cleaned = cleaned.replace(/\s*```\s*$/i, "")
  // If model prefixed with prose, find the first { and slice from there.
  const firstBrace = cleaned.indexOf("{")
  if (firstBrace > 0) cleaned = cleaned.slice(firstBrace)
  // And trim any trailing text after the last closing brace.
  const lastBrace = cleaned.lastIndexOf("}")
  if (lastBrace > 0 && lastBrace < cleaned.length - 1) {
    cleaned = cleaned.slice(0, lastBrace + 1)
  }
  return cleaned
}

function isAutoGeneratedPost(value: unknown): value is AutoGeneratedPost {
  if (!value || typeof value !== "object") return false
  const v = value as Record<string, unknown>
  if (typeof v.title !== "string" || v.title.trim().length === 0) return false
  if (typeof v.excerpt !== "string") return false
  if (!Array.isArray(v.tags)) return false
  if (!v.tags.every((t) => typeof t === "string")) return false
  if (typeof v.body_md !== "string" || v.body_md.trim().length < 200) return false
  return true
}

function normalizeTags(input: string[], seed: readonly string[]): string[] {
  const seen = new Set<string>()
  for (const tag of [...input, ...seed]) {
    const cleaned = tag.trim().toLowerCase()
    if (cleaned.length > 0 && cleaned.length <= 30) seen.add(cleaned)
  }
  return Array.from(seen).slice(0, 5)
}

/**
 * News-grounded prompt: every post is anchored on a real, recent news angle
 * (last 90 days) about how the chosen tech focus is changing the chosen
 * vertical. The Google Search tool is enabled at the call site so Gemini
 * can retrieve and cite actual sources rather than hallucinating trends.
 */
function buildPrompt(angle: Angle, recentTitles: string[]): string {
  const recentList =
    recentTitles.length > 0
      ? `\n\nRecent Vetd post titles to AVOID duplicating or closely paraphrasing:\n${recentTitles
          .map((t) => `  - ${t}`)
          .join("\n")}`
      : ""

  const verticalExamples = angle.vertical.examples.join(", ")
  const verticalPains = angle.vertical.pains
    .map((p) => `- ${p}`)
    .join("\n")

  return `Write a blog post for the Vetd blog.

Vertical (target reader): ${angle.vertical.label} (${verticalExamples})
Tech focus: ${angle.tech.label} — ${angle.tech.description}

Common pains for this vertical you can weave in where relevant:
${verticalPains}

Step 1 (research, internal — do NOT include in the output):
Use Google Search to find recent news, product launches, studies, or trend
reports from the LAST 90 DAYS about how ${angle.tech.label.toLowerCase()} is
helping ${angle.vertical.label.toLowerCase()} grow, attract more customers,
or solve operational problems. Pick ONE concrete news angle, study, or
launch as the anchor. Prefer reputable sources (industry publications,
mainstream tech press, vendor announcements with clear dates). If nothing
recent surfaces, fall back to a credible news item from the last 12 months.

Step 2 (write the post):
Write a blog post that:
  1. Opens by grounding the reader in the SPECIFIC news angle you found
     (date, what happened, why it matters). Do not bury the news.
  2. Translates the news into concrete implications for a ${angle.vertical.label.toLowerCase()} owner.
  3. Shows what they should consider doing about it, in plain English, and
     where ${angle.tech.label.toLowerCase()} like the kind Vetd builds fits in.
  4. Cites the source(s) inline with a markdown link near where you reference them.
  5. Closes with a soft call to action toward Vetd (contact, financing, or products).

Tone: educational and convincing, not salesy. The reader is a busy owner.${recentList}

${JSON_INSTRUCTION}`
}

async function fetchRecentTitles(
  admin: ReturnType<typeof createAdminClient>,
  limit = 30,
): Promise<{ titles: string[]; slugs: Set<string> }> {
  const { data } = await admin
    .from("blog_posts")
    .select("title_en, slug")
    .order("created_at", { ascending: false })
    .limit(limit)
  const titles = (data ?? []).map((r) => r.title_en)
  const slugs = new Set((data ?? []).map((r) => r.slug))
  return { titles, slugs }
}

/**
 * Resolve a unique slug given a base. Postgres has the unique constraint as
 * a backstop, but resolving up front lets us keep the slug human-readable
 * (`title-2`, `title-3`) instead of a UUID suffix.
 */
function resolveUniqueSlug(base: string, taken: Set<string>): string {
  if (!taken.has(base)) return base
  for (let i = 2; i < 50; i++) {
    const candidate = `${base}-${i}`
    if (!taken.has(candidate)) return candidate
  }
  // Pathological fallback. Postgres unique constraint will still catch any
  // collision past this; the calling code surfaces that as an error.
  return `${base}-${Date.now()}`
}

export type RunDailyOptions = {
  /** Force a specific vertical. Falls back to today's rotation when omitted. */
  verticalId?: string
  /** Force a specific tech focus. Falls back to today's rotation when omitted. */
  techId?: string
  /**
   * When true, schedule the post for 24h from now (status='scheduled').
   * When false (default), insert as draft. Reads `BLOG_AUTO_PUBLISH=true` if
   * not provided so ops can flip without redeploying the cron route.
   */
  autoPublish?: boolean
  /**
   * When true (default), also generate Spanish translations of title,
   * excerpt, and body so the post is bilingual on day one. When false,
   * insert EN-only and let the user translate manually from the editor.
   */
  translate?: boolean
}

/**
 * Daily content generation pipeline. Picks today's (vertical, tech) angle,
 * grounds Gemini on recent news via Google Search, dedupes against recent
 * titles, and inserts a row into `blog_posts`. Default insert is
 * `status='draft'` so the user reviews before anything goes live; flip
 * `BLOG_AUTO_PUBLISH=true` (or the option) to schedule with a 24h buffer
 * instead.
 */
export async function runDailyGeneration(
  options: RunDailyOptions = {},
): Promise<GenerateDailyResult> {
  if (!process.env.GEMINI_API_KEY) {
    return { ok: false, error: "GEMINI_API_KEY missing" }
  }

  const angle = resolveAngle({
    verticalId: options.verticalId,
    techId: options.techId,
  })

  const admin = createAdminClient()
  const { titles: recentTitles, slugs: existingSlugs } =
    await fetchRecentTitles(admin)

  let attempt = 0
  let post: AutoGeneratedPost | null = null
  let sources: GroundingSource[] = []
  let lastError = ""
  while (attempt < 2 && !post) {
    attempt += 1
    const result = await generateGroundedText({
      prompt: buildPrompt(angle, recentTitles),
      systemInstruction: `You are a senior content writer for the Vetd blog. ${VETD_CONTEXT} ${HOUSE_STYLE} You research with Google Search and ground every claim in the news you find.`,
      temperature: 0.6,
      // MEDIUM balances cost and depth on flash-lite — long-form blog bodies
      // need more reasoning than tag/excerpt utility calls. Bump to HIGH if
      // bodies still feel shallow; drop to MINIMAL if cost becomes a concern.
      thinkingLevel: ThinkingLevel.MEDIUM,
    })
    if (!result.ok) {
      lastError = result.error
      continue
    }

    const cleaned = extractJsonPayload(result.text)
    try {
      const parsed = JSON.parse(cleaned)
      if (!isAutoGeneratedPost(parsed)) {
        lastError = "Gemini response did not match expected JSON shape"
        continue
      }

      // Dedup by similar-title check against the recent titles list.
      const lower = parsed.title.toLowerCase()
      const tooSimilar = recentTitles.some((t) => {
        const a = t.toLowerCase()
        return a === lower || a.includes(lower) || lower.includes(a)
      })
      if (tooSimilar) {
        lastError = `Duplicate-style title: ${parsed.title}`
        // Append the rejected title to the avoid list for the retry.
        recentTitles.push(parsed.title)
        continue
      }
      post = parsed
      sources = result.sources
    } catch (err) {
      lastError = err instanceof Error ? err.message : String(err)
    }
  }

  if (!post) {
    return {
      ok: false,
      error: `Gemini generation failed after ${attempt} attempt(s): ${lastError}`,
      verticalId: angle.vertical.id,
      techId: angle.tech.id,
    }
  }

  const slug = resolveUniqueSlug(titleToSlug(post.title), existingSlugs)
  const tags = normalizeTags(
    post.tags,
    [angle.vertical.id.replace(/-/g, " "), angle.tech.id.replace(/-/g, " ")],
  )

  const titleEn = post.title.trim()
  const excerptEn = post.excerpt.trim()
  const bodyEn = post.body_md.trim()

  // Bilingual day one: translate title, excerpt, and body in parallel.
  // Failures don't block the insert — partial translations still ship the
  // EN row and the meta.translation_errors field surfaces what fell over so
  // the user can retry from the editor.
  const shouldTranslate = options.translate ?? true
  const translation = { title: false, excerpt: false, body: false }
  let titleEs: string | null = null
  let excerptEs: string | null = null
  let bodyEs: string | null = null
  const translationErrors: Record<string, string> = {}

  if (shouldTranslate) {
    const [titleRes, excerptRes, bodyRes] = await Promise.all([
      translateFieldEnToEs("title", titleEn),
      excerptEn
        ? translateFieldEnToEs("excerpt", excerptEn)
        : Promise.resolve({ ok: true as const, text: "" }),
      translateFieldEnToEs("body", bodyEn),
    ])

    if (titleRes.ok && titleRes.text.trim()) {
      titleEs = titleRes.text.trim()
      translation.title = true
    } else if (!titleRes.ok) {
      translationErrors.title = titleRes.error
    }

    if (excerptRes.ok && excerptRes.text.trim()) {
      excerptEs = excerptRes.text.trim()
      translation.excerpt = true
    } else if (!excerptRes.ok) {
      translationErrors.excerpt = excerptRes.error
    } else {
      // Source excerpt was empty; treat as a successful skip.
      translation.excerpt = true
    }

    if (bodyRes.ok && bodyRes.text.trim()) {
      bodyEs = bodyRes.text.trim()
      translation.body = true
    } else if (!bodyRes.ok) {
      translationErrors.body = bodyRes.error
    }
  }

  // ES is only "complete enough" for the public /es route when both title
  // and body translations landed (mirrors the bilingual-fallback rule in
  // lib/blog/queries.ts: untranslated posts are hidden from /es).
  const esComplete = translation.title && translation.body

  const autoPublish =
    options.autoPublish ?? process.env.BLOG_AUTO_PUBLISH === "true"
  const status = autoPublish ? "scheduled" : "draft"
  const publishedAt = autoPublish
    ? new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString()
    : null

  const meta: { [key: string]: Json } = {
    auto: true,
    auto_vertical: angle.vertical.id,
    auto_tech: angle.tech.id,
    auto_angle_id: angleId(angle),
    auto_generated_at: new Date().toISOString(),
    auto_model: "gemini",
    auto_attempt: attempt,
    auto_translated: shouldTranslate,
    auto_translation_complete: esComplete,
    auto_grounded: true,
    auto_sources: sources.map((s) => ({ uri: s.uri, title: s.title })),
  }
  if (Object.keys(translationErrors).length > 0) {
    meta.auto_translation_errors = translationErrors
  }

  const { data, error } = await admin
    .from("blog_posts")
    .insert({
      slug,
      title_en: titleEn,
      title_es: titleEs,
      excerpt_en: excerptEn || null,
      excerpt_es: excerptEs,
      body_md_en: bodyEn,
      body_md_es: bodyEs,
      tags,
      status,
      published_at: publishedAt,
      meta,
    })
    .select("id, slug")
    .single()

  if (error || !data) {
    return {
      ok: false,
      error: error?.message ?? "Failed to insert generated post",
      verticalId: angle.vertical.id,
      techId: angle.tech.id,
    }
  }

  return {
    ok: true,
    postId: data.id,
    slug: data.slug,
    verticalId: angle.vertical.id,
    techId: angle.tech.id,
    title: titleEn,
    mode: status,
    sourceCount: sources.length,
    translation,
  }
}

/** Re-exported for the admin UI dropdown so the matrix stays in one place. */
export { VERTICALS, TECH_FOCUS, angleForDate }
