export const INDUSTRY_OPTIONS = [
  "Legal",
  "Restaurant",
  "Cafe",
  "Hospitality",
  "Events",
  "Retail",
  "Dental",
  "Healthcare",
  "Pet Services",
  "Finance",
  "Real Estate",
  "Wholesale",
  "Logistics",
  "Transportation",
  "Manufacturing",
  "Software",
  "Education",
  "Fitness",
  "Beauty & Wellness",
  "Construction",
  "Home Services",
  "Automotive",
  "Nonprofit",
] as const

export type Industry = (typeof INDUSTRY_OPTIONS)[number]
