-- Leads UI fields: lead scoring, stated intent, budget band, and a short
-- human-readable display number (L-231) derived from an identity column.

alter table public.clients
  add column score int check (score between 0 and 100),
  add column intent text,
  add column budget text,
  add column lead_number bigint generated by default as identity unique;

create index clients_score_idx on public.clients (score desc);
create index clients_lead_number_idx on public.clients (lead_number);
