export const Constants = {
    public: {
        Enums: {
            client_source: [
                "contact_form",
                "referral",
                "cold_outreach",
                "social",
                "event",
                "rep_field",
                "other",
            ],
            client_status: ["lead", "qualified", "active_client", "archived", "lost"],
            commission_ledger_status: ["pending", "paid", "voided"],
            document_kind: ["proposal", "contract", "sow", "nda", "invoice_terms"],
            document_status: ["draft", "sent", "viewed", "signed", "void"],
            employment_status: ["active", "terminated"],
            interaction_type: [
                "call",
                "email",
                "meeting",
                "note",
                "follow_up",
                "visit",
            ],
            payment_status: ["unpaid", "link_sent", "paid", "refunded", "failed"],
            project_product_type: [
                "business_website",
                "mobile_app",
                "web_app",
                "ai_integration",
            ],
            project_stage: [
                "proposal",
                "negotiation",
                "active",
                "completed",
                "cancelled",
            ],
            subscription_status: ["pending", "active", "at_risk", "canceled"],
            task_status: ["todo", "doing", "review", "done"],
            user_role: ["admin", "editor", "sales_rep", "viewer"],
        },
    },
};
